---
language: minimal
services: docker

env:
  matrix:
    - BASE_IMAGE: fauust/docker-systemd:debian-10
    - BASE_IMAGE: fauust/docker-systemd:debian-sid
    - BASE_IMAGE: fauust/docker-systemd:ubuntu-18.04
    - BASE_IMAGE: fauust/docker-systemd:ubuntu-20.04

before_install:
  - |
    if ! git diff --name-only HEAD^ | grep -qvE '(.md)|(.pdf)'
    then
      echo "Only doc files were updated, not running the CI."
      exit
    fi
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

addons:
  apt:
    update: true

cache:
  directories:
    - $HOME/.cache/pre-commit

jobs:
  include:
    - name: lint with pre-commit
      language: python
      install: skip
      before_install: skip
      script:
        - pip install pre-commit
        - pre-commit run -c .travis-pre-commit-config.yaml -a

script:
  - docker build . -t fauust/docker-ansible:${BASE_IMAGE/fauust\/docker-systemd:/} --build-arg base_image=${BASE_IMAGE/fauust\/docker-systemd:/}
  - docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/mnt -w /mnt wagoodman/dive:latest --ci fauust/docker-ansible:${BASE_IMAGE/fauust\/docker-systemd:/}
  - docker run --rm fauust/docker-ansible:${BASE_IMAGE/fauust\/docker-systemd:/} python3 -V
