ARG base_image=fedora-39
FROM ghcr.io/fauust/docker-systemd:"$base_image"

RUN set -eux \
  && . /etc/os-release \
  && yum -y install \
    ca-certificates \
    python3 \
    python3-dnf \
    sudo \
  && if [ "$VERSION_ID" = 41 ] || [ "$VERSION_ID" = 42 ]; then \
        yum -y install python3-libdnf5; \
     fi \
  # clean doc \
  && rm -rf /usr/share/doc \
    /usr/share/man \
  # clean yum/rpm \
  && yum clean all

VOLUME ["/sys/fs/cgroup"]
CMD ["/lib/systemd/systemd"]
