ARG base_image=alpine-3.18
FROM ghcr.io/fauust/docker-systemd:"$base_image"

RUN set -eux \
    && apk add --update --no-cache \
    bash \
    ca-certificates \
    iproute2 \
    lsb-release \
    python3

VOLUME ["/sys/fs/cgroup"]
CMD ["/sbin/init"]
